/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: bachlamanh406 (https://sketchfab.com/bachlamanh406)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rb20-2b81733c08c847a58ed531566688a464
Title: Rb20
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.187, 0.27, -0.046]} rotation={[Math.PI / 2, 0, 0]} scale={0.359}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Material.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials['Material.002']}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.material_0}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials['Material.003']}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials['Material.006']}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials['Material.005']}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials['Material.007']}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.material_0}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.material_0}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials['Material.004']}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.material_0}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials.material_0}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials['Material.008']}
        position={[0.187, 0.27, -0.046]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.359}
      />
    </group>
  )
}

useGLTF.preload('/car.glb')
